### ISSUE TITLE
Support for Reborn

### ISSUE THREAD

**Issue by Tea23** [victorvde/dota2_nohats#17]
I don't even know how feasible this is. Reborn probably has anti-anti-hat technology or something I dunno.

gameinfo still exists but it has a different file extension - works in the same way as gameinfo.txt.

**Comment by fernandodeperto** [comment]
I tried for a while today to update the package to the current version of dota. I had some problems with the python code, mainly because of different things in the vpk that the code was not expecting, for example items with no heroes attached to them.

The first one that appears is:

```
KVList([('name', 'Default Cursor Pack'), ('prefab', 'cursor_pack'), ('creation_date', '2015-08-26'), ('image_inventory', 'econ/cursor_pack/cursor_pack_default'), ('item_name', '#DOTA_Item_Default_Cursor_Pack'), ('baseitem', '1')])
Traceback (most recent call last):
  File "nohats.py", line 1274, in <module>
    nohats()
  File "nohats.py", line 48, in nohats
    defaults = get_defaults(d)
  File "nohats.py", line 140, in get_defaults
    assert hero is not None, id
AssertionError: 202
```

I don't code in Python and I have no knowledge about the way Valve packs the assets, so I am not qualified to update this. This is unfortunate because I really miss this package.

Note: I tried to contact the developer, but so far no luck. 

Note 2: I also tried to ignore the cases where items had no heroes attacked to them, but other problemas related to the VPKs appear after that, so I gave up.
